* Define Array ADT 
A one-dimensional array is a collection of contiguous elements in which individual
elements are identified by a unique integer subscript starting with zero. Once an
array is created, its size cannot be changed.
- Array( size ): Creates a one-dimensional array consisting of size
  elements with each element initially set to None. size must be greater
  than zero.
- length (): Returns the length or number of elements in the array.
- getitem ( index ): Returns the value stored in the array at element
  position index. The index argument must be within the valid range.
  Accessed using the subscript operator.
- setitem ( index, value ): Modifies the contents of the array element at
  position index to contain value. The index must be within the valid
  range. Accessed using the subscript operator.
- clearing( value ): Clears the array by setting every element to value.
- iterator (): Creates and returns an iterator that can be used to traverse
  the elements of the array.
